# QA Environment Configurations

# UI Application URLs
saucedemo.url=https://www.saucedemo.com
orangehrm.url=https://opensource-demo.orangehrmlive.com

# UI App Credentials (Example)
saucedemo.username=standard_user
saucedemo.password=secret_sauce
orangehrm.username=Admin
orangehrm.password=admin123

# Database Settings
db.url=jdbc:postgresql://localhost:5432/automation_db_qa
db.username=postgres
db.password=postgres
db.driver=org.postgresql.Driver

# API Settings
api.base.uri=https://reqres.in/api

# Email Server Settings (MailHog standard ports inside container)
smtp.host=localhost
smtp.port=1025
smtp.username=
smtp.password=
smtp.inbox.port=8025

# Browser Settings
browser.headless=true
browser.slowmo=0
browser.viewport.width=1280
browser.viewport.height=720
browser.video.enabled=true
browser.video.path=target/videos/
browser.tracing.enabled=true
browser.tracing.path=target/traces/
